Feature/url slugs
santiagogustavo/blogster pull request #3
Opened 2018-02-27 15:51 UTC by santiagogustavo

Implementa a funcionalidade de slugs para as URLs de posts e categorias.
Utiliza o gem FriendlyId para tratar rotas com ids, títulos (para posts) e nomes (para categorias).
Atualiza todos os pontos onde esses modelos são referenciados e tratados pelos controllers :)

2018-02-27 18:51 UTC, guilpejon requested changes

2018-02-27 18:51 UTC, guilpejon commented on blogster/app/controllers/comments_controller.rb
> +    @fallback = post_path(@comment.post)
Se você não tiver usando `@fallback` na view você não precisa declarar como variável global aqui. Se não tiver usando essa variável também você pode passar direto o valor dela pro `redirect_back`, aí fica mais limpo o código.

2018-02-27 18:51 UTC, guilpejon commented on blogster/app/controllers/posts_controller.rb
> +    @post.slug = nil
Por que você tá setando o slug como nil aqui?

2018-02-27 18:56 UTC, santiagogustavo commented on blogster/app/controllers/comments_controller.rb
> +    @fallback = post_path(@comment.post)
Coloquei essa variável por conta do @comment.destroy. A ideia seria voltar para o post, mesmo se tiver algum problema e cair no fallback

2018-02-27 18:58 UTC, santiagogustavo commented on blogster/app/controllers/posts_controller.rb
> +    @post.slug = nil
O slug não atualizava quando um post era editado, problema relacionado com o regenerate_slug padrão do FriendlyId. Fiz um override no modelo, vou verificar se continua funcionando sem essa atribuição para nil.

2018-02-28 12:27 UTC, santiagogustavo commented
@guilpejon fiz os ajustes que foram comentados, não fazia sentido manter aquelas linhas mesmo

2018-02-28 12:53 UTC, guilpejon approved these changes

2018-02-28 12:54 UTC, merged